let svggroup = d3.select("#triple-well")

svggroup.append("g")
  .attr("transform", "translate(19, 95)")
  .append(() => MathJax.tex2svg(String.raw`\circ`).querySelector("svg"))
  .attr("color", "#ededed")
svggroup.append("g")
  .attr("transform", "translate(83, 80)")
  .append(() => MathJax.tex2svg(String.raw`\Uparrow`).querySelector("svg"))
  .attr("color", "#ededed")
svggroup.append("g")
  .attr("transform", "translate(147, 80)")
  .append(() => MathJax.tex2svg(String.raw`\Downarrow`).querySelector("svg"))
  .attr("color", "#ededed")